### ISSUE TITLE
Add E2E Testing for Ingress Support

### ISSUE THREAD

**Issue by edavidj** [application-stacks/runtime-component-operator#105]
- Add a new e2e test that runs on the new minikube job rather than the 3.11 cluster
- If there is relevant unit testing to add for utils, controller, etc. can bundle it into this issue

**Comment by leochr** [comment]
@halim-lee recently created some ingress e2e for the minikube test scenario.

**Comment by leochr** [comment]
Thanks @halim-lee for adding Ingress e2e tests
