### ISSUE TITLE
Remove spec.service.provides and spec.service.consumes

### ISSUE THREAD

**Issue by navidsh** [application-stacks/runtime-component-operator#130]
Once https://github.com/application-stacks/runtime-component-operator/issues/64 is delivered, the operator will be relying on the Service Binding Operator to provide service-to-service binding.
At that point, we can remove `spec.service.provides` and `spec.service.consumes` to fully rely on the SBO to providing binding between different backing services (including Runtime Component Operator based applications).

**This is a breaking change.**

**Comment by arthurdm** [comment]
As an extension to this work, we should also:

* remove `bindings.*`
* add `service.bindable`
  * a boolean (default `false`) that signals the RC Operator to create a `Secret` with the service URL and (if applicable) the route URL, referencing the secret from `status.binding.name`.
  * this replaces `bindings.expose.enabled`

**Comment by leochr** [comment]
Resolved via PR https://github.com/application-stacks/runtime-component-operator/pull/231
