### ISSUE TITLE
Fix itermittent E2E failures

### ISSUE THREAD

**Issue by edavidj** [application-stacks/runtime-component-operator#142]
**Note**: feel free to comment intermittent failures that you encounter below for reference

The following e2e tests present regular issues with having to restart tests:
- [ ] Image Stream
- [ ] Autoscaling
- [x] Service Monitor
- [ ] Knative

Cluster related issues that occur for all tests intermittently:
- [x] ImagePullBackOff on operator deployment

These are normally caused by things such as:
- Concurrency issues
- Unreliable operations that rely on the cluster or travis scripts (i.e. manually created resources, cluster wide resources, etc.)
- Timing issues (i.e. waiting with a `time.Sleep` instead of `wait.Poll`)

**Comment by InfTkm** [comment]
An intermittent error happened in the Travis build of Open Liberty Operator.
<img width="1262" alt="Screen Shot 2020-06-18 at 4 56 28 PM" src="https://user-images.githubusercontent.com/25573786/85071000-cb21a280-b184-11ea-84d2-22eeab90b9c3.png">

**Comment by edavidj** [comment]
Generic ImagePullBackOff on operator deployment for `RuntimeBasicTest` [here](https://travis-ci.org/github/application-stacks/runtime-component-operator/jobs/700138895). Has happened on a wide variety of tests, but don't see it often.

**Comment by InfTkm** [comment]
> Generic ImagePullBackOff on operator deployment for `RuntimeBasicTest` [here](https://travis-ci.org/github/application-stacks/runtime-component-operator/jobs/700138895). Has happened on a wide variety of tests, but don't see it often.

A similar one happened in OpenLiberty pull policy test: [waiting for the operator to be deployed](https://travis-ci.org/github/OpenLiberty/open-liberty-operator/jobs/700197834).

**Comment by edavidj** [comment]
These haven't come up in the form listed in this issue in sometime, closing for now and we can open a new one as more pop up (especially with the new testing cluster around)
