### ISSUE TITLE
Handle image streams w/out breaking OpenShift 3 Registry Image Pullthrough functionality

### ISSUE THREAD

**Issue by ron1** [application-stacks/runtime-component-operator#155]
### What did you do?

- Enable OpenShift 3.11 Internal Registry [Image Pullthrough](https://docs.openshift.com/container-platform/3.11/install_config/registry/extended_registry_configuration.html#middleware-repository-pullthrough)
- Create an image stream using a reference policy type of Local for the RuntimeComponent CR applicationImage
- Deploy a RuntimeComponent whose applicationImage is the name of the above image stream

### What did you expect to see?

I expected the Pod created by the RCO to include an image that references the image in the internal registry.

### What did you see instead?

Instead, the Pod image was re-written to reference the image at the remote source. As a result, the image is pulled from the remote source rather than the internal registry mirrored cache.

### Environment

OCP 3.11

**Comment by navidsh** [comment]
Hi @ron1, thanks for opening this issue. The issue should be fixed in https://github.com/application-stacks/runtime-component-operator/pull/156.

**Comment by navidsh** [comment]
Delivered the fix in #156. Closing this one.
Opened https://github.com/OpenLiberty/open-liberty-operator/issues/206 to fix for Open Liberty Operator
