### ISSUE TITLE
Update Travis build definition to stop running e2e tests on OCP 3.11

### ISSUE THREAD

**Issue by navidsh** [application-stacks/runtime-component-operator#161]
Since CP4Apps 4.x requires OpenShift 4.x for installation, update test scripts to stop running tests on OpenShift 3.11. Only Cloud Pak 3.x supports OpenShift 3.11 which only installs an older version of the Appsody Operator.

[Knowledge Center for CP4Apps](https://www.ibm.com/support/knowledgecenter/SSCSJL/welcome.html) lists supported OpenShift versions.

**Comment by ron1** [comment]
The RCO is available independent of CP4Apps in OperatorHub and is currently in use by OCP 3.11 users. Consider supporting OCP 3.11 as long as 3.11 is supported by Red Hat.

**Comment by navidsh** [comment]
Hi @ron1, we will continue to support the `<= v0.7.0` of the operator in OCP 3.11 until it's supported by Red Hat if issues arise.
New versions of the operator won't be supported on OCP 3.11 though.

**Comment by navidsh** [comment]
Delivered the changes in both RCO and Open Liberty operators. Closing.
