### ISSUE TITLE
Operator SDK latest version

### ISSUE THREAD

**Issue by kishkulk** [application-stacks/runtime-component-operator#169]
Hi Team, 

   I see that the operator-sdk 0.15.2 is pretty old, do you have any plans to upgrade the operator-sdk version?

**Comment by leochr** [comment]
@kishkulk yes, we are planning to upgrade it to Operator SDK 1.0. The testing framework has completely changed in 1.0. So we would need to repurpose our tests to validate that nothing has broken.

**Comment by kishkulk** [comment]
@leochr thanks for your reply, any release date is planned as such ?

**Comment by leochr** [comment]
@kishkulk let you know when we have a release date. Thanks.

**Comment by kishkulk** [comment]
@leochr we are using runtime component operator framework for our product. As the runtime component operator serves majority of operator functionality it really helped us to use it and develop the operator. So is there a way that I contribute to this project?

**Comment by leochr** [comment]
@kishkulk we welcome contributions. Perhaps having a meeting would be easier to understand how you use Runtime Component Operator and where/how you can contribute. Considering the time zone difference, may I ask you to book a meeting? Preferably, sometimes next week. Thank you.

**Comment by leochr** [comment]
Resolved by https://github.com/application-stacks/runtime-component-operator/pull/185
