### ISSUE TITLE
Specify security context

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#170]
The operator should specify some security context by default to deploy pod/containers securely (i.e. runAsNonRoot). 

It'll also be good to consider a way for users to add (or override) their own security context configurations.

Note: checkout [kube-linter](https://github.com/stackrox/kube-linter) for some best practices.

**Comment by halim-lee** [comment]
Covered by:
https://github.com/application-stacks/runtime-component-operator/pull/356
https://github.com/application-stacks/runtime-component-operator/pull/362
