### ISSUE TITLE
Remove embedded certs

### ISSUE THREAD

**Issue by arthurdm** [application-stacks/runtime-component-operator#171]
This workitem will track the removal of `spec.service.certificate` and `spec.route.certificate`, relying on their `ref` variants.  We have run into lots of issues related to mismatched Cert-Manager versions, etc, so just using the ref should help prevent this. 

The value-add from the Operator is that it will watch the referenced Secret for any changes and update the corresponding resources.

**Comment by leochr** [comment]
Resolved by PR https://github.com/application-stacks/runtime-component-operator/pull/190
