### ISSUE TITLE
Allow configuration of Deployment strategy

### ISSUE THREAD

**Issue by arthurdm** [application-stacks/runtime-component-operator#173]
We need to surface a way to configure the [Deployment.spec.strategy](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies) and [StatefulSet.spec.updateStrategy](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies) that we create.

**Comment by leochr** [comment]
@halim-lee please look into this next. Thank you.
