### ISSUE TITLE
Convert tests to run on new framework

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#178]
Existing tests are not compatible with operator-sdk 1.x. Convert existing tests to one of the new testing framework (kuttl, scorecard, env-test). Tests related to kAppNav integration and servicebinding doesn't have to be ported, but we still want to keep generating Application definition)

e2e tests at https://github.com/application-stacks/runtime-component-operator/tree/master/test/e2e : 
- [x] runtime_basic.go - Jason
- [x] runtime_pullpolicy.go - Bradley
- [x] runtime_probe.go - Iain
- [x] runtime_autoscaling.go - Iain
- [x] runtime_imagestream.go - Iain
- [x] runtime_knative.go - Iain
- [x] runtime_storage.go -Iain
- [x] runtime_servicemonitor.go - Iain
- [ ] runtime_test.go - I don't believe this is actually a test, but rather the entry point for e2e tests (of all framework?)
- [x] ~runtime_kappnav.go~ - kAppNav integration will be removed in v1, but operator will continue to generate Application definition. Operator will need to be enhanced to add this support. So we don't need to convert this now.
- [x] ~runtime_certmanager.go~ - Cert manager support will change in v1, so we don't need to convert this now.
- [ ] ~runtime_servicebinding.go~ - Service binding support will change in v1, so we don't need to convert this now. - handled via https://github.com/application-stacks/runtime-component-operator/issues/239

Unit tests: handled via https://github.com/application-stacks/runtime-component-operator/issues/237

**Comment by yongja79** [comment]
The script to run the tests in travis will also need to be updated [e2e.sh](https://github.com/application-stacks/runtime-component-operator/blob/master/scripts/e2e.sh)
