### ISSUE TITLE
Runtime Component Operator release that will run with k8s 1.22.  

### ISSUE THREAD

**Issue by anneqm** [application-stacks/runtime-component-operator#212]
## Feature Request
We would like to keep reference RCO in the CP4apps 5.1 documentation, but we need a version that moves to the k8s 1.22 dependence and removes the APIs previously deprecated and removed in k8s 1.22. 

### Is your feature request related to a problem?

A clear and concise description of what the problem is. Example: "I have an issue when (...)"
Currently, CP4Apps 5.1 documentation points to RCO.. CP4Apps is "supposed to" support OCP releases within 30 days of GA. So 
OLO with k8s is I believe the higher priority, however, both would be idea. ...  

### Describe the solution you'd like
a version of RCO with k8s 1.22...    .. 
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Comment by greglanthier** [comment]
In case it helps anyone following along this is a test I've cobbled together using [kind](https://kind.sigs.k8s.io/) to detect whether RCO would run in a v1.22 cluster:

```bash
kind create cluster --image kindest/node:v1.22.1 && \
curl -sSfL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.18.3/install.sh | bash -s -- "v0.18.3" && \
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml && \
kubectl create -f https://operatorhub.io/install/runtime-component-operator.yaml && \
timeout 2m bash -c 'until kubectl wait deployment.apps -n operators runtime-component-operator --for=condition=available --timeout=10s; do sleep 5; done' || echo "It did not work"
```

When I run this test with v1.22.1 I see something like this:
```bash
...
Error from server (NotFound): deployments.apps "runtime-component-operator" not found
Error from server (NotFound): deployments.apps "runtime-component-operator" not found
Error from server (NotFound): deployments.apps "runtime-component-operator" not found
Error from server (NotFound): deployments.apps "runtime-component-operator" not found
It did not work
```

What I expect to see is something like this (when I run with v1.21.2):

```bash
Error from server (NotFound): deployments.apps "runtime-component-operator" not found
Error from server (NotFound): deployments.apps "runtime-component-operator" not found
Error from server (NotFound): deployments.apps "runtime-component-operator" not found
deployment.apps/runtime-component-operator condition met
```

This is likely related to #203 in that the RCO version available in the marketplace uses some deprecated APIs that have been removed from v1.22.  These deprecated APIs may include files matching the following queries:

- https://github.com/application-stacks/runtime-component-operator/search?q=apiextensions.k8s.io%2Fv1beta1
- https://github.com/application-stacks/runtime-component-operator/search?q=rbac.authorization.k8s.io%2Fv1beta1
- https://github.com/application-stacks/runtime-component-operator/search?q=admissionregistration.k8s.io%2Fv1beta1

**Comment by leochr** [comment]
Closing as completed. RCO 0.8.0 added support for this.
