### ISSUE TITLE
Consistent binding schemes across namespaces

### ISSUE THREAD

**Issue by seabaylea** [application-stacks/runtime-component-operator#23]
### Is your feature request related to a problem?

We want to be able to promote microservices across dev/staging/prod, and the most common way of doing this will be to use separate namespaces for each environment.

The way that OpenAPI service binding works today requires the user to specify the namespace, and then uses that namespace name as part of the injected configuration name.

This means that we cannot promote a microservice without both code and configuration changes.

### Describe the solution you'd like

One approach to solving this wold be to allow the `consumes` statement to default to using the current namespace if no namespace is specified, and in that scenario not include the namespace in the injected configuration. Where a namespace is specified, that would continue to be provided in the config.

This approach should be additive and therefore non-breaking and avoid config name collisions.

**Comment by arthurdm** [comment]
+1

I believe we have half of that working today:  if a namespace is not specified the Operator will look for the Secret in the current namespace.   

The part that is missing is omitting the namespace in the injected / mounted path.

**Comment by yharish991** [comment]
PR https://github.com/application-stacks/runtime-component-operator/pull/27 for this issue has been merged

**Comment by seabaylea** [comment]
@yharish991 When testing this, the injected env vars start with `_`, eg:

```
    Environment:
      _CATALOG_USERNAME:    <set to the key 'username' in secret 'storefront-dev-catalog'>    Optional: true
      _CATALOG_PASSWORD:    <set to the key 'password' in secret 'storefront-dev-catalog'>    Optional: true
      _CATALOG_URL:         <set to the key 'url' in secret 'storefront-dev-catalog'>         Optional: true
      _CATALOG_HOSTNAME:    <set to the key 'hostname' in secret 'storefront-dev-catalog'>    Optional: true
      _CATALOG_PROTOCOL:    <set to the key 'protocol' in secret 'storefront-dev-catalog'>    Optional: true
      _CATALOG_PORT:        <set to the key 'port' in secret 'storefront-dev-catalog'>        Optional: true
      _CATALOG_CONTEXT:     <set to the key 'context' in secret 'storefront-dev-catalog'>     Optional: true
      _CUSTOMER_USERNAME:   <set to the key 'username' in secret 'storefront-dev-customer'>   Optional: true
      _CUSTOMER_PASSWORD:   <set to the key 'password' in secret 'storefront-dev-customer'>   Optional: true
      _CUSTOMER_URL:        <set to the key 'url' in secret 'storefront-dev-customer'>        Optional: true
      _CUSTOMER_HOSTNAME:   <set to the key 'hostname' in secret 'storefront-dev-customer'>   Optional: true
      _CUSTOMER_PROTOCOL:   <set to the key 'protocol' in secret 'storefront-dev-customer'>   Optional: true
      _CUSTOMER_PORT:       <set to the key 'port' in secret 'storefront-dev-customer'>       Optional: true
```

Is that expected?

**Comment by navidsh** [comment]
@seabaylea Can you please verify which version of the operator you are using?

We had a very similar issue that was fixed in https://github.com/application-stacks/runtime-component-operator/pull/46.

**Comment by seabaylea** [comment]
I'm using Appsody Operator v0.4.0:

```
Containers:
  appsody-operator:
    Image:         appsody/application-operator:0.4.0
```

**Comment by navidsh** [comment]
@seabaylea can you please retry with `v0.4.1`?

**Comment by yharish991** [comment]
@seabaylea i just tested with Appsody Operator v0.4.0 and works fine for me. 
```
 Environment:
      SVC1_USERNAME:  <set to the key 'username' in secret 'default-svc1'>  Optional: true
      SVC1_PASSWORD:  <set to the key 'password' in secret 'default-svc1'>  Optional: true
      SVC1_URL:       <set to the key 'url' in secret 'default-svc1'>       Optional: true
      SVC1_HOSTNAME:  <set to the key 'hostname' in secret 'default-svc1'>  Optional: true
      SVC1_PROTOCOL:  <set to the key 'protocol' in secret 'default-svc1'>  Optional: true
      SVC1_PORT:      <set to the key 'port' in secret 'default-svc1'>      Optional: true
      SVC1_CONTEXT:   <set to the key 'context' in secret 'default-svc1'>   Optional: true
```
The fix #46 that @navidsh mentioned is released in Runtime Component Operator v0.4.1 and the Appsody Operator v0.4.0 uses Runtime Component Operator v0.4.1 .

**Comment by navidsh** [comment]
@seabaylea can you please delete the operator pod so it pulls the latest image once starting? If you are still seeing the issue, please share your `AppsodyApplication` (if possible) so we can recreate it and get it fixed

**Comment by seabaylea** [comment]
@navidsh yes - redeploying the Appsody operator to pick up the new version of 0.4.0 remove the prefix.

Thanks!

**Comment by leochr** [comment]
Thanks for confirming @seabaylea
