### ISSUE TITLE
Manually run the e2e tests on OCP 4.9 

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#238]
Get a OCP 4.9 cluster from Fyre and install the latest operator driver and run the unit tests and e2e tests to verify it works fine. This can be done by manually executing the commands from the travis builds: https://github.com/application-stacks/runtime-component-operator/blob/master/.travis.yml

**Comment by idlewis** [comment]
This is done. All tests passed, with the operator installed via OLM using:
`operator-sdk run bundle --install-mode OwnNamespace....`
as per the travis builds, and the tests running through scorecard
