### ISSUE TITLE
Update the asserts on Deployment/StatefulSet status

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#274]
Few tests assert by checking the status of Deployment and/or StatefulSet. Only replicas and/or readyReplicas are checked. We should also check updatedReplicas to ensure it has the expected value. Otherwise, the old pod that's in ready state will be considered while evaluating pass/fail. Checking all 3 values will ensure that the Deployment/StatfulSet is in expected state.

- [x] Delivered to RCO
- [x] Delivered to OLO

**Comment by yongja79** [comment]
Fixed in OLO with [PR295](https://github.com/OpenLiberty/open-liberty-operator/pull/295)
