### ISSUE TITLE
RCO release 0.8.2

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#397]
- Include the fix for the pull secret issue (https://github.com/application-stacks/runtime-component-operator/pull/377)
- Switch sample app to `icr.io/appcafe/open-liberty/samples/getting-started`
- Update version to 0.8.2
- Enable minikube tests

**Comment by Elyytscha** [comment]
Hello,

would it be possible to integrate also https://github.com/application-stacks/runtime-component-operator/issues/359 in 0.8.2, we can't upgrade our runtime component safely when we have to patch those limits manually, our actual rco instance was using about ~350 MB Ram constantly last week.

**Comment by leochr** [comment]
@idlewis please add change log and kubectl and kustomize artifacts (under deploy/releases/0.8.2). Reference PR for 0.8.1 release: https://github.com/application-stacks/runtime-component-operator/pull/338/files
