### ISSUE TITLE
Track items to synchronize 

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#430]
- [x] Update kind tests and kube version ([WLO PR](https://github.com/WASdev/websphere-liberty-operator/pull/294))
- [x] Fix e2e tests to non-OpenShift ([WLO PR](https://github.com/WASdev/websphere-liberty-operator/pull/301/files))

**Comment by halim-lee** [comment]
Delivered by https://github.com/application-stacks/runtime-component-operator/pull/495
