### ISSUE TITLE
Update build and test scripts of RCO and OLO

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#457]
Blocked by: WLO issue https://github.com/WASdev/websphere-liberty-operator/issues/396

- [ ] Update build and test scripts to sync with WLO
- [ ] Clean-up/archive unused scripts, makefile instructions and functions

- [ ] Delivered to OLO

**Comment by idlewis** [comment]
@leochr There are still some significant differences in the .one-pipeline.yaml script between RCO and the others. Apart from that I believe this is all done.
