### ISSUE TITLE
Updated service binding request

### ISSUE THREAD

**Issue by arthurdm** [application-stacks/runtime-component-operator#47]
Transferring [this item](https://github.com/appsody/appsody-operator/issues/206).

In the [service binding spec](https://github.com/application-stacks/service-binding-specification) topics 2, 3 and 4 apply to this Operator.  

Topic 2 is easy to comply, as our binding data structure looks almost like the spec.

Topic 4 should also not be too complex, as we would just need to adjust the path we're mounting.

Topic 3 is the tricky one, because we want to make the `ServiceBindingRequest` CR an embedded component of our `RuntimeComponent` CR - but in a way that's easier to write, since the Operator can infer a lot of the details.   

We also need to think, in terms of user configuration, how to combine the app -> app native support our Operator has with the app -> resource support we're delegating.  

One thought is to make our CR's `service.consumes` an array of `backingServiceSelectors` (being renamed to `services` I believe), so that we can map 1-to-1 into the `ServiceBindingRequest` we create on the component's behalf.   We would then just need to map those fields to the app -> app support we have to today, so it's consistent regardless of the service we're binding to.

**Comment by navidsh** [comment]
Closing this in favour of #100
