### ISSUE TITLE
Default route for latest RCO 1.0 sample does not work 

### ISSUE THREAD

**Issue by mtamboli** [application-stacks/runtime-component-operator#472]
### What did you do?

I installed RCO as mentioned [here](https://github.com/application-stacks/runtime-component-operator/wiki). 
Created an instance and tried to access default route.

### What did you expect to see?

A clear and concise description of what you expected to happen (or insert a code snippet). If possible, add `RuntimeComponent` CR.

![image](https://user-images.githubusercontent.com/29490950/227652985-6c140798-9f16-447b-9d86-bc07b50f930b.png)

### What did you see instead?

A clear and concise description of what you expected to happen (or insert a code snippet).

### Environment

Describe the environment (e.g OpenShift/Kubernetes version information).
OCP 4.12

### Possible solution

Need to update port 9080 to 9443

Once change the port, application is accessible. This change is needed as TLS is enabled by default.

**Comment by mtamboli** [comment]
@leochr I am not able to add labels to this issue. Can you please `bug` and `svt' label to this? It helps with our queries.

**Comment by leochr** [comment]
@mtamboli sure, added labels

**Comment by leochr** [comment]
@mtamboli This is addressed in the multi-arch driver for RCO. Please validate and close issue. Thank you
