### ISSUE TITLE
Add reconciled version

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#489]
Add status.versions.reconciled for RCO. 

WLO and OLO already include it

- [x] add checks to RuntimeOperations test in RCO
- [x] add equivalent tests to OLO
- [x] add equivalent tests to WLO

**Comment by leochr** [comment]
@idlewis It seems WLO needs the tests (although WLO is checked off above)

**Comment by idlewis** [comment]
> @idlewis It seems WLO needs the tests (although WLO is checked off above)

I clearly can't read, I thought I had done this.
PR opened for WLO is WASdev/websphere-liberty-operator#480
