### ISSUE TITLE
Network Policies are not cleaned up by operator after switching to Knative

### ISSUE THREAD

**Issue by Jonathan-Maciel** [application-stacks/runtime-component-operator#500]
### What did you do?

Running an application on a P cluster, I first deployed the application with it serving over port 9443. I then modified the deployment to be serverless with Knative just by adding `createKnativeService: true` and moving to unsecure port 9080.

### What did you expect to see?

I expected to see the application deployed over http with Knative. 

### What did you see instead?

I saw that the page would not load as there was no response from the server. 

### Environment

OCP P cluster. WLO 1.2.

### Possible solution

There was a Network Policy lingering for the application that specified the secure port which is not supported by Knative. It would be helpful to have the operator clean up the Network Policy that is associated with the older deployment.

**Comment by leochr** [comment]
Official OLO and RCO 1.2.0 drivers are also now available and should contain this fix

**Comment by leochr** [comment]
Fixed. Closing
