### ISSUE TITLE
Update k8s.gcr.io to registry.k8s.io

### ISSUE THREAD

**Issue by halim-lee** [application-stacks/runtime-component-operator#502]
There was an announcement in https://kubernetes.io/blog/2023/03/10/image-registry-redirect/ : "older k8s.gcr.io registry will be redirected to registry.k8s.io with the eventual goal of sunsetting k8s.gcr.io"

Need to switch to registry.k8s.io for our test pause image

**Comment by leochr** [comment]
Thank you. Delivered. Closing.
