### ISSUE TITLE
Support creating OpenShift VCS labels

### ISSUE THREAD

**Issue by seabaylea** [application-stacks/runtime-component-operator#52]
### Is your feature request related to a problem?

There's a standard set of labels OpenContainers labels/annotations which allow you to specify information such as where the source repository is and what revision is used.

By default, microservices created by the Appsody project set the following labels:
```
    image.opencontainers.org/created: "2020-03-17T11:48:58Z"
    image.opencontainers.org/documentation: https://github.com/seabaylea/backend
    image.opencontainers.org/revision: 8be7def88e73b0e311b8517bd0a960bc03f5282d-modified
    image.opencontainers.org/source: https://github.com/seabaylea/backend/tree/master
    image.opencontainers.org/url: https://github.com/seabaylea/backend
```

However, OpenShift uses its own labels to store version control information.

### Describe the solution you'd like

Where the application provides open container label, but not the corresponding OpenShift annotations, the Runtime Component Operator could create the OpenShift equivalents (when deploying to OpenShift).

The list of OpenShift labels and annotations are here:
https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc

The relevant two in this scenario are:
```
app.openshift.io/vcs-uri
app.openshift.io/vcs-ref
```

**Comment by leochr** [comment]
Resolved by PR https://github.com/application-stacks/runtime-component-operator/pull/54
