### ISSUE TITLE
Ability to set specific NodePort

### ISSUE THREAD

**Issue by EnriqueL8** [application-stacks/runtime-component-operator#53]
## Feature Request
Currently the operator sets a random port for the service when using NodePort. As @leochr mentioned NodePort shouldn’t be used in production at all, but this could be used for testing.
Issue [#720](https://github.com/appsody/appsody/issues/720)

### Is your feature request related to a problem?
Could this be something that could be added to the CRD?

**Comment by yharish991** [comment]
Resolved by PR #60
