### ISSUE TITLE
Create a sample Quarkus application that uses the Runtime Component Operator

### ISSUE THREAD

**Issue by arthurdm** [application-stacks/runtime-component-operator#61]
This issue will populate [this repo](https://github.com/application-stacks/sample-quarkus-with-operator) with a sample application running on Quarkus (can be one from the Quarkus community, either MicroProfile or Spring Boot) and using the Runtime Component Operator for a simple `kubectl apply -f app-deploy.yaml` deployment.

**Comment by leochr** [comment]
@JusteenR could you please look into this? It'll be alright to put the unit test enhancements on hold for now.

**Comment by arthurdm** [comment]
Maybe we can use this sample: https://quarkus.io/guides/security-jwt

**Comment by JusteenR** [comment]
The sample application is made at https://github.com/application-stacks/sample-quarkus-with-operator
