### ISSUE TITLE
Adopt service binding specification

### ISSUE THREAD

**Issue by arthurdm** [application-stacks/runtime-component-operator#64]
This issue / epic will track the adoption of the relevant parts of the [service binding specification](https://github.com/application-stacks/service-binding-specification).

In particular:
* Built-in support in the `RuntimeComponent` CR to gather enough information to create (under the covers) a `ServiceBindingRequest` [CR](https://github.com/application-stacks/service-binding-specification#request-service-binding).  The user won't need to specify anything pertaining to the applicationSelector / application fields.
  * Perhaps a new `bindings` top level element will be the best idea, deprecating our current usage of `service.consumes[]`

* Making our Operator `bindable`, since we expose RESTful services.  Should be as per [this definition](https://github.com/application-stacks/service-binding-specification#making-a-service-bindable)
  * This would also imply a new way of doing `service.produces` and using the proposed [binding schema](https://github.com/application-stacks/service-binding-specification#service-binding-schema)

* Mounting data as per the [spec's definition](https://github.com/application-stacks/service-binding-specification#mounting-binding-information)
  * In the future also allowing env var injection as per [this issue](https://github.com/application-stacks/service-binding-specification/issues/15)

**Comment by seabaylea** [comment]
@arthurdm Would the move to `bindings` from `service.[provides|consumes]` just be a refactor?

I think it would also be useful to start to consider how we'll handle Kafka topics for µservice<->µservice message passing. In most cases that will be the same as what we're doing for REST today (the receiver just needs to be told what topic the sender is using), but there are more advanced cases where the publisher may need to create a KafkaTopic CR as well.

**Comment by arthurdm** [comment]
hey @seabaylea - we're thinking the `services` parts of the `bindings` element should closely resemble the parts of the underlying `ServiceBinding` CR that the Operator will create on the user's behalf - this allows for consistent config and ease of use (i.e. can copy/paste snippets from one to the other).  

But ya - all those things are in the `consumer` side.  If there are more advanced options for the `producer` side this issue would be the place to discuss, as we can (and should) definitely take that into account.

**Comment by navidsh** [comment]
Delivered. Closing.
